version: 2

# 构建环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # 指定 Python 版本

# 如果不用 conda，也可以用 pip 安装
python:
  install:
    - requirements: requirements.txt

# Sphinx 配置
sphinx:
  configuration: docs/source/conf.py
